name = "ReactiveKernels"
uuid = "78e9f072-d36b-4c73-b7a3-751b0eb26cf9"
authors = ["Nikolas Siccha <nikolassiccha@gmail.com>"]
version = "0.1.0"

[deps]
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"

[weakdeps]
MutatingFunctions = "8a4c2d94-4b3b-4f9e-be63-a3c0cd816e3a"

[extensions]
ReactiveKernelsMutatingFunctionsExt = "MutatingFunctions"

[compat]
ForwardDiff = "0.10, 1"
MutatingFunctions = "0.1"
RuntimeGeneratedFunctions = "0.5"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "ForwardDiff", "InteractiveUtils", "LinearAlgebra", "Test"]
